#!/bin/sh
exec /usr/local/bin/mine/remux/binaries/wine/mono/bin/mono $MONO_OPTIONS /usr/local/bin/mine/remux/binaries/wine/mono/lib/mono/mono-configuration-crypto/4.5/mono-configuration-crypto.exe "$@"
