#!/bin/sh
MONO_GC_PARAMS="nursery-size=64m,$MONO_GC_PARAMS" exec /usr/local/bin/mine/remux/binaries/wine/mono/bin/mono $MONO_OPTIONS /usr/local/bin/mine/remux/binaries/wine/mono/lib/mono/xbuild/14.0/bin/xbuild.exe "$@"
